import { z } from 'zod';
import rawManifest from './voiceManifest.json';

// Which lines have a voice file (generated by `npm run voice -- build`, tools/voice/README.md).
// Bundled with the app so a bubble knows at once whether to show 🔊; absent = no button.

const VoiceManifestSchema = z.object({
  version: z.literal(1),
  provider: z.string(),
  lines: z.record(z.string(), z.object({ hash: z.string() })),
});

export type VoiceManifest = z.infer<typeof VoiceManifestSchema>;

/** Parses a manifest; a broken one means "no voice lines" rather than a crashed screen. */
export function parseVoiceManifest(raw: unknown): VoiceManifest {
  const parsed = VoiceManifestSchema.safeParse(raw);
  return parsed.success ? parsed.data : { version: 1, provider: 'none', lines: {} };
}

/** Looks up line ids in a manifest. */
export function createVoiceLookup(manifest: VoiceManifest) {
  const ids = new Set(Object.keys(manifest.lines));
  return {
    has: (lineId: string): boolean => ids.has(lineId),
    url: (lineId: string): string | null =>
      ids.has(lineId) ? `${import.meta.env.BASE_URL}audio/voice/${lineId}.mp3` : null,
    size: ids.size,
  };
}

export type VoiceLookup = ReturnType<typeof createVoiceLookup>;

export const voiceLookup: VoiceLookup = createVoiceLookup(parseVoiceManifest(rawManifest));

/** True when line `lineId` has a pre-generated voice file. */
export const hasVoice = (lineId: string): boolean => voiceLookup.has(lineId);
